### YamlMime:Landing
title: Dokumentacja ról usługi Azure AD — Azure AD
summary: Dostępem do zasobów usługi Azure AD zarządza kontrola dostępu oparta na rolach w usłudze Azure AD. Twórz role niestandardowe, przypisuj role korzystające z jednostek administracyjnych w celu ograniczenia zakresu kontroli, przypisuj dostęp aplikacji do grup lub użytkowników, zarządzaj uprawnieniami za pomocą usługi Privileged Identity Management (PIM) lub deleguj uprawnienia do dystrybucji zadań zarządzania tożsamościami.
metadata:
  title: Dokumentacja ról usługi Azure Active Directory
  description: Dowiedz się, jak zarządzać dostępem w organizacji za pomocą ról usługi Azure AD.
  services: active-directory
  ms.service: active-directory
  ms.subservice: roles
  manager: daveba
  ms.topic: landing-page
  ms.date: 10/19/2020
  author: curtand
  ms.author: curtand
  ms.openlocfilehash: 8dd6ac6fef0dbc84c77ccacfd048b2af21771f6a
  ms.sourcegitcommit: d60976768dec91724d94430fb6fc9498fdc1db37
  ms.translationtype: HT
  ms.contentlocale: pl-PL
  ms.lasthandoff: 12/02/2020
  ms.locfileid: "96499207"
landingContent:
- title: Informacje o rolach usługi Azure AD
  linkLists:
  - linkListType: overview
    links:
    - text: Omówienie kontroli dostępu na podstawie ról w usłudze Azure AD
      url: custom-overview.md
  - linkListType: concept
    links:
    - text: Omówienie ról usługi Azure AD
      url: concept-understand-roles.md
    - text: Informacje o jednostkach administracyjnych w usłudze Azure AD
      url: administrative-units.md
    - text: Zarządzanie przypisaniami ról za pomocą grup w chmurze
      url: groups-concept.md
- title: Rozpoczęcie pracy
  linkLists:
  - linkListType: quickstart
    links:
    - text: Udzielanie uprawnień do tworzenia nieograniczonych rejestracji aplikacji
      url: quickstart-app-registration-limits.md
- title: Delegowanie ról
  linkLists:
  - linkListType: how-to-guide
    links:
    - text: Delegowanie ról według zadania
      url: delegate-by-task.md
    - text: Delegowanie zarządzania aplikacjami
      url: delegate-app-roles.md
- title: Przypisywanie ról do użytkowników
  linkLists:
  - linkListType: how-to-guide
    links:
    - text: Tworzenie ról niestandardowych
      url: custom-create.md
    - text: Przypisywanie ról przy użyciu interfejs API programu Graph
      url: custom-assign-graph.md
    - text: Przypisywanie przy użyciu programu PowerShell
      url: custom-assign-powershell.md
    - text: Przypisywanie ról przy użyciu interfejs API programu Graph
      url: custom-assign-graph.md
- title: Przypisywanie ról do grup
  linkLists:
  - linkListType: how-to-guide
    links:
    - text: Tworzenie grup z możliwością przypisania do roli
      url: groups-create-eligible.md
    - text: Przypisywanie roli do grupy w chmurze
      url: groups-assign-role.md
    - text: Ustawianie grupy jako kwalifikującej się do usługi PIM
      url: groups-pim-eligible.md
    - text: Wyświetlanie przypisań dla grupy
      url: groups-view-assignments.md
- title: Zarządzanie zakresem za pomocą jednostek administracyjnych
  linkLists:
  - linkListType: how-to-guide
    links:
    - text: Dodawanie i usuwanie jednostek administracyjnych
      url: admin-units-manage.md
    - text: Przypisywanie użytkowników do jednostek
      url: admin-units-add-manage-users.md
    - text: Przypisywanie grup do jednostek
      url: admin-units-add-manage-groups.md
    - text: Przypisywanie grup z zakresem
      url: admin-units-assign-roles.md
