### YamlMime:Landing
title: Platforma Kubernetes z włączoną usługą Azure Arc
summary: Dowiedz się, jak zarządzać klastrami Kubernetes przy użyciu usługi Azure Arc
metadata:
  title: Platforma Kubernetes z włączoną usługą Azure Arc
  description: Dowiedz się, jak zarządzać komputerami lokalnymi na platformie Azure
  author: shashankbarsin
  ms.service: azure-arc
  ms.topic: landing-page
  ms.date: 03/02/2021
  ms.author: shasb
  ms.openlocfilehash: f97b1560e062d1849f726baff8cd66d8e75f8b7f
  ms.sourcegitcommit: b4647f06c0953435af3cb24baaf6d15a5a761a9c
  ms.translationtype: MT
  ms.contentlocale: pl-PL
  ms.lasthandoff: 03/02/2021
  ms.locfileid: "101647850"
landingContent:
- title: Łączenie klastrów Kubernetes z platformą Azure przy użyciu usługi Azure Arc
  linkLists:
  - linkListType: overview
    links:
    - text: Co to jest platforma Kubernetes z włączoną usługą Azure Arc?
      url: overview.md
    - text: Program weryfikacji usługi Azure Arc
      url: validation-program.md
  - linkListType: concept
    links:
    - text: Architektura agentów
      url: conceptual-agent-architecture.md
    - text: Konfiguracje i GitOps
      url: conceptual-configurations.md
    - text: Często zadawane pytania
      url: faq.md
- title: Rozpoczęcie pracy
  linkLists:
  - linkListType: quickstart
    links:
    - text: Łączenie klastra z usługą Azure Arc
      url: quickstart-connect-cluster.md
- title: Wdrażanie konfiguracji przy użyciu metodyki GitOps
  linkLists:
  - linkListType: tutorial
    links:
    - text: Wdrażanie konfiguracji przy użyciu metodyki GitOps
      url: tutorial-use-gitops-connected-cluster.md
- title: Konfigurowanie, zarządzanie i monitorowanie klastrów
  linkLists:
  - linkListType: how-to-guide
    links:
    - text: Wdrażanie elementów chart programu Helm przy użyciu metodyki GitOps
      url: use-gitops-with-helm.md
    - text: Wymuś metodykę GitOps przy użyciu usługi Azure Policy
      url: use-azure-policy.md
    - text: Wdrażanie obciążeń usługi Azure IoT Edge
      url: deploy-azure-iot-edge-workloads.md
- title: Weryfikacja koncepcji
  linkLists:
  - linkListType: sample
    links:
    - text: Szybkie rozpoczynanie pracy
      url: https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/
- title: Architektura referencyjna
  linkLists:
  - linkListType: architecture
    links:
    - text: Zarządzanie wdrożeniami i konfiguracjami dla hybrydowych klastrów Kubernetes
      url: /azure/architecture/hybrid/arc-hybrid-kubernetes
