### YamlMime:Landing
title: Platforma Kubernetes z usługą Azure Arc (wersja zapoznawcza)
summary: Dowiedz się, jak zarządzać klastrami Kubernetes przy użyciu usługi Azure Arc
metadata:
  title: Platforma Kubernetes z usługą Azure Arc
  description: Dowiedz się, jak zarządzać komputerami lokalnymi na platformie Azure
  author: 
  ms.service: azure-arc
  ms.topic: landing-page
  ms.date: 06/26/2020
  ms.author: 
  ms.openlocfilehash: 9eeddfefe451eb524484df8a1986c7ec736c4c0f
  ms.sourcegitcommit: d79513b2589a62c52bddd9c7bd0b4d6498805dbe
  ms.translationtype: HT
  ms.contentlocale: pl-PL
  ms.lasthandoff: 12/18/2020
  ms.locfileid: "97674376"
landingContent:
- title: Łączenie klastrów Kubernetes z platformą Azure przy użyciu usługi Azure Arc
  linkLists:
  - linkListType: overview
    links:
    - text: Co to jest platforma Kubernetes z włączoną usługą Azure Arc?
      url: overview.md
  - linkListType: quickstart
    links:
    - text: Połączenie klastra
      url: connect-cluster.md
  - linkListType: how-to-guide
    links:
    - text: Wdrażanie konfiguracji przy użyciu metodyki GitOps
      url: use-gitops-connected-cluster.md
    - text: Wdrażanie elementów chart programu Helm przy użyciu metodyki GitOps
      url: use-gitops-with-helm.md
    - text: Wymuś metodykę GitOps przy użyciu usługi Azure Policy
      url: use-azure-policy.md
    - text: Wdrażanie obciążeń usługi Azure IoT Edge
      url: deploy-azure-iot-edge-workloads.md
- title: Weryfikacja koncepcji
  linkLists:
  - linkListType: sample
    links:
    - text: Szybkie rozpoczynanie pracy
      url: https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/
- title: Architektura referencyjna
  linkLists:
  - linkListType: architecture
    links:
    - text: Zarządzanie wdrożeniami i konfiguracjami dla hybrydowych klastrów Kubernetes
      url: /azure/architecture/hybrid/arc-hybrid-kubernetes
